<?php header('Content-Type:text/xml') ?>
<?php echo '<?' ?>xml version="1.0" encoding="UTF-8"<?php echo '?>' ?><?php echo '<?' ?>xml-stylesheet type="text/xsl" href="<?php echo SITE_URL . '/inc/robots/sitemaps/post-sitemap.xsl' ?>"<?php echo '?>' ?>

<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php 
	
		$cats = models_DB::get('SELECT id, url, title, image, time_update FROM ' . CATEGORY_TABLE . ' WHERE the_status=\'publish\'' );
		foreach($cats as $cat)
		{
			?>
			<url>
				<loc><?php hcv_url('p', $cat['url'], $cat['id']) ?></loc>
				<lastmod><?php echo date('Y-m-d', $cat['time_update']); ?></lastmod>
				<changefreq>weekly</changefreq>
				<priority>0.4</priority>
				
				
				<?php 
					if(!empty($cat['image']) && (0))
					{
						?>
						<image:image>
							<image:loc><?php echo $cat['image'] ?></image:loc>
							<image:title><?php echo $cat['title'] ?></image:title>
							<image:caption><?php echo $cat['title'] ?></image:caption>
						</image:image>
						<?php
					}
				?>
				
			</url>
			<?php
		}
	?>
	
	
</urlset>

<!-- XML Sitemap generated by Yoast Hoang Cong Vuong -->