<?php header('Content-Type:text/xml') ?>
<?php echo '<?' ?>xml version="1.0" encoding="UTF-8"<?php echo '?>' ?><?php echo '<?' ?>xml-stylesheet type="text/xsl" href="<?php echo SITE_URL . '/inc/robots/sitemaps/post-sitemap.xsl' ?>"<?php echo '?>' ?>

<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php 
	
		$posts = models_DB::get('SELECT id, seo, url, title, image, time_update FROM ' . POST_TABLE . ' WHERE the_status=\'publish\'');
		 
        
        foreach($posts as $post)
		{
			$seo_info = json_decode($post['seo'], TRUE);
			  
			if($seo_info['index']=='index')
			{
			?>
			<url>
				<loc><?php hcv_url('p', $post['url'], $post['id']) ?></loc>
				<lastmod><?php echo date('Y-m-d', $post['time_update']); ?></lastmod>
				<changefreq>weekly</changefreq>
				<priority>0.6</priority>
				
				
				<?php 
					if(!empty($post['image']) && (0))
					{
					?>
					<image:image>
						<image:loc><?php echo $post['image'] ?></image:loc>
						<image:title><?php echo $post['title'] ?></image:title>
						<image:caption><?php echo $post['title'] ?></image:caption>
					</image:image>
					<?php
					}
				?>
				
			</url>
			<?php
			}
		}
	?>
	
	
</urlset>

<!-- XML Sitemap generated by Yoast Hoang Cong Vuong -->